spring:
  application:
    name: SmartBot
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:database/schema/master.xml
logging:
  level:
    dev:
      langchain4j: DEBUG
