spring:
  application:
    name: SmartBot
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:database/schema/master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVER_URL}
          jwk-set-uri: ${AUTHORIZATION_SERVER_URL}${AUTHORIZATION_SERVER_CONTEXT_PATH}/oauth2/jwks
  cloud:
    vault:
      enabled: true
      host: ${VAULT_HOST}
      token: ${VAULT_TOKEN}

logging:
  level:
    dev:
      langchain4j: ${LOG_LEVEL}
    root: INFO
    smartbot: ${LOG_LEVEL}