version: "3.2"
services:
  activemq:
    image: antonw/activemq-jmx
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
      - "1099:1099"
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartbot
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10